//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigLeaf.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FigLeaf.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fig Leaf.
        /// </summary>
        public static string Common_AppTitle {
            get {
                return ResourceManager.GetString("Common_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string Common_Culture {
            get {
                return ResourceManager.GetString("Common_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Common_ErrorFormat {
            get {
                return ResourceManager.GetString("Common_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Common_Language {
            get {
                return ResourceManager.GetString("Common_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a target file/folder that does not exist in source:
        ///{0}
        ///Delete it and all such files and folders (type &apos;Y&apos;) or cancel Pack operation (type &apos;N&apos;)?.
        /// </summary>
        public static string Console_ConfirmDeleteFormat {
            get {
                return ResourceManager.GetString("Console_ConfirmDeleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file not found.
        /// </summary>
        public static string Console_NoSettings {
            get {
                return ResourceManager.GetString("Console_NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to define restore source.
        /// </summary>
        public static string Console_RestoreSourceNotDefined {
            get {
                return ResourceManager.GetString("Console_RestoreSourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;.zip&apos; extension to file name.
        /// </summary>
        public static string Core_ArchiveNameRule_AddZipExtension {
            get {
                return ResourceManager.GetString("Core_ArchiveNameRule_AddZipExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep original file name.
        /// </summary>
        public static string Core_ArchiveNameRule_KeepOriginal {
            get {
                return ResourceManager.GetString("Core_ArchiveNameRule_KeepOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string Core_FileProcessor_Cancel {
            get {
                return ResourceManager.GetString("Core_FileProcessor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder {0}.
        /// </summary>
        public static string Core_FileProcessor_CreateDirFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_CreateDirFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create thumbnail file {0}.
        /// </summary>
        public static string Core_FileProcessor_CreatingThumbFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_CreatingThumbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete target file {0}.
        /// </summary>
        public static string Core_FileProcessor_DeletingObsoleteTargetFileFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_DeletingObsoleteTargetFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete thumbnail file {0}.
        /// </summary>
        public static string Core_FileProcessor_DeletingObsoleteThumbFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_DeletingObsoleteThumbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete target folder without source {0} (with {1} sub-folders and {2} files).
        /// </summary>
        public static string Core_FileProcessor_DeletingTargetDirWoSourceFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_DeletingTargetDirWoSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete target file without source {0}.
        /// </summary>
        public static string Core_FileProcessor_DeletingTargetFileWoSourceFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_DeletingTargetFileWoSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created target folders: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_CreatedTargetDirsFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_CreatedTargetDirsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created target files: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_CreatedTargetFilesFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_CreatedTargetFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created target thumbnails: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_CreatedTargetThumbsFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_CreatedTargetThumbsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done in {0:hh\:mm\:ss} ({1} ms.).
        /// </summary>
        public static string Core_FileProcessor_LogSum_DoneInFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_DoneInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed source folders: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_ProcessedSourceDirsFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_ProcessedSourceDirsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed source files: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_ProcessedSourceFilesFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_ProcessedSourceFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed obsolete target files: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_RemovedObsoleteTargetFilesFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_RemovedObsoleteTargetFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed obsolete target thumbnails: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_RemovedObsoleteTargetThumbsFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_RemovedObsoleteTargetThumbsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed target folders without source: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_RemovedTargetDirsWoSourceFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_RemovedTargetDirsWoSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed target files without source: {0}.
        /// </summary>
        public static string Core_FileProcessor_LogSum_RemovedTargetFilesWoSourceFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_LogSum_RemovedTargetFilesWoSourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target dir must be empty.
        /// </summary>
        public static string Core_FileProcessor_NonEmptyTargetDirError {
            get {
                return ResourceManager.GetString("Core_FileProcessor_NonEmptyTargetDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder does not exist.
        /// </summary>
        public static string Core_FileProcessor_NoSourceDirError {
            get {
                return ResourceManager.GetString("Core_FileProcessor_NoSourceDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack file {0} to {1}.
        /// </summary>
        public static string Core_FileProcessor_PackingFileFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_PackingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip FigLeaf folder {0}.
        /// </summary>
        public static string Core_FileProcessor_SkipFigLeafDirFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_SkipFigLeafDirFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack from {0} to {1}.
        /// </summary>
        public static string Core_FileProcessor_StartPackFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_StartPackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack from {0} to {1}.
        /// </summary>
        public static string Core_FileProcessor_StartUnpackFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_StartUnpackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack file {0} to {1}.
        /// </summary>
        public static string Core_FileProcessor_UnpackingFileFormat {
            get {
                return ResourceManager.GetString("Core_FileProcessor_UnpackingFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate password rule.
        /// </summary>
        public static string Core_PasswordRule_BadFormula {
            get {
                return ResourceManager.GetString("Core_PasswordRule_BadFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate password rule for file.
        /// </summary>
        public static string Core_PasswordRule_BadFormulaFormat {
            get {
                return ResourceManager.GetString("Core_PasswordRule_BadFormulaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom rule.
        /// </summary>
        public static string Core_PasswordRule_Custom {
            get {
                return ResourceManager.GetString("Core_PasswordRule_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name numbers followed by master password.
        /// </summary>
        public static string Core_PasswordRule_FileNameNumbersPlusPassword {
            get {
                return ResourceManager.GetString("Core_PasswordRule_FileNameNumbersPlusPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password only.
        /// </summary>
        public static string Core_PasswordRule_Password {
            get {
                return ResourceManager.GetString("Core_PasswordRule_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password followed by file name numbers.
        /// </summary>
        public static string Core_PasswordRule_PasswordPlusFileNameNumbers {
            get {
                return ResourceManager.GetString("Core_PasswordRule_PasswordPlusFileNameNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to make thumbnail for the file {0}: {1}.
        /// </summary>
        public static string Core_ThumbErrorFormat {
            get {
                return ResourceManager.GetString("Core_ThumbErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ui_Actions_Cancel {
            get {
                return ResourceManager.GetString("Ui_Actions_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (detailed logging).
        /// </summary>
        public static string Ui_Actions_DetailedLogging {
            get {
                return ResourceManager.GetString("Ui_Actions_DetailedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Ui_Actions_Header {
            get {
                return ResourceManager.GetString("Ui_Actions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Ui_Actions_Log {
            get {
                return ResourceManager.GetString("Ui_Actions_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack to ...
        /// </summary>
        public static string Ui_Actions_RestoreTargetTo {
            get {
                return ResourceManager.GetString("Ui_Actions_RestoreTargetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Ui_Actions_UpdateTarget {
            get {
                return ResourceManager.GetString("Ui_Actions_UpdateTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a target file/folder that does not exist in source:
        ///{0}
        ///Delete it and all such files and folders (Yes) or cancel Pack operation (No)?.
        /// </summary>
        public static string Ui_ConfirmDeleteFormat {
            get {
                return ResourceManager.GetString("Ui_ConfirmDeleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify empty folder to unpack files.
        /// </summary>
        public static string Ui_Dialogs_RestoreTarget {
            get {
                return ResourceManager.GetString("Ui_Dialogs_RestoreTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language to {0} and restart application?.
        /// </summary>
        public static string Ui_Dialogs_SwitchLanguageFormat {
            get {
                return ResourceManager.GetString("Ui_Dialogs_SwitchLanguageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string Ui_Folders_Add {
            get {
                return ResourceManager.GetString("Ui_Folders_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm target files &amp; folders deletion.
        /// </summary>
        public static string Ui_Folders_ConfirmDelete {
            get {
                return ResourceManager.GetString("Ui_Folders_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the Pack target folder(s) structure will be synced with the source.
        ///If some files/folders does not exist in the source - they needs to be deleted.
        ///Enable this option to prevent unintended deletion that can be made by mistake.
        ///.
        /// </summary>
        public static string Ui_Folders_ConfirmDelete_Tip {
            get {
                return ResourceManager.GetString("Ui_Folders_ConfirmDelete_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string Ui_Folders_Delete {
            get {
                return ResourceManager.GetString("Ui_Folders_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude FigLeaf folder.
        /// </summary>
        public static string Ui_Folders_ExcludeFigLeafDir {
            get {
                return ResourceManager.GetString("Ui_Folders_ExcludeFigLeafDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can store this program in some subfolder of your source folder.
        ///With this option enabled, this subfolder will not be packed to the target..
        /// </summary>
        public static string Ui_Folders_ExcludeFigLeafDir_Tip {
            get {
                return ResourceManager.GetString("Ui_Folders_ExcludeFigLeafDir_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup multiple folders.
        /// </summary>
        public static string Ui_Folders_HasMultiple {
            get {
                return ResourceManager.GetString("Ui_Folders_HasMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Ui_Folders_Header {
            get {
                return ResourceManager.GetString("Ui_Folders_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack.
        /// </summary>
        public static string Ui_Folders_RestoreHeader {
            get {
                return ResourceManager.GetString("Ui_Folders_RestoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Ui_Folders_Source {
            get {
                return ResourceManager.GetString("Ui_Folders_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Ui_Folders_Target {
            get {
                return ResourceManager.GetString("Ui_Folders_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Ui_Security_ArchiveNameRule {
            get {
                return ResourceManager.GetString("Ui_Security_ArchiveNameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule formula.
        /// </summary>
        public static string Ui_Security_CustomPasswordRule {
            get {
                return ResourceManager.GetString("Ui_Security_CustomPasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Ui_Security_Header {
            get {
                return ResourceManager.GetString("Ui_Security_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password.
        /// </summary>
        public static string Ui_Security_MasterPassword {
            get {
                return ResourceManager.GetString("Ui_Security_MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password rule.
        /// </summary>
        public static string Ui_Security_PasswordRule {
            get {
                return ResourceManager.GetString("Ui_Security_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can build your own password rules using formulas. The following variables and functions allowed:
        ///- FileName - name of the file being processed, with extension and without full path
        ///- Password - master password
        ///- Reverse(string) - reverse string, Reverse(IMG_0123.jpg) = gpj.3210_GMI
        ///- Upper(string) - uppercase string, Upper(IMG_0123.jpg) = IMG_0123.JPG
        ///- Lower(string) - lowercase string, Lower(IMG_0123.jpg) = img_0123.jpg
        ///- Digits(string) - extract digits from string, Digits(IMG_0123.jpg) = 1234
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ui_Security_PasswordRule_Tip {
            get {
                return ResourceManager.GetString("Ui_Security_PasswordRule_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string Ui_Security_ShowPassword {
            get {
                return ResourceManager.GetString("Ui_Security_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate thumbnails.
        /// </summary>
        public static string Ui_Thumbnails_Enable {
            get {
                return ResourceManager.GetString("Ui_Thumbnails_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string Ui_Thumbnails_Header {
            get {
                return ResourceManager.GetString("Ui_Thumbnails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in pixels.
        /// </summary>
        public static string Ui_Thumbnails_Size {
            get {
                return ResourceManager.GetString("Ui_Thumbnails_Size", resourceCulture);
            }
        }
    }
}
